language: java


jobs:
  includes:
    - stage: "on PR"
      if: env(TRAVIS_PULL_REQUEST_BRANCH)!=''
      script: 
        - echo "${TRAVIS_PULL_REQUEST_BRANCH}"
    - stage: "on master"
      if: env(TRAVIS_PULL_REQUEST_BRANCH)=''
      script:
        - echo "${TRAVIS_PULL_REQUEST_BRANCH}"
