language: java


jobs:
  include:
    - stage: "on PR"
      if: branch='master' AND head_branch!='master'
      script: 
        - echo "on PR"
    - stage: "on master"
      if: branch='master' AND head_branch='master'
      script:
        - echo "on master"
