language: java


jobs:
  include:
    - stage: "on PR"
      name: "on pr"
      script: 
        - echo "on PR"
    - stage: "on master"
      name: "on master"
      script:
        - echo "on master"
