language: java


jobs:
  include:
    - stage: "on PR"
      if: env(TRAVIS_PULL_REQUEST_BRANCH)!=''
      script: 
        - echo "${TRAVIS_PULL_REQUEST_BRANCH} on PR"
    - stage: "on master"
      if: env(TRAVIS_PULL_REQUEST_BRANCH)=''
      script:
        - echo "${TRAVIS_PULL_REQUEST_BRANCH} on master"
