language: java
os: linux
dist: xenial


jobs:
  include:
    - stage: "on PR"
      if: NOT type = cron AND type = pull_request
      name: "on pr"
      script: 
        - echo "on PR"
    - stage: "on master"
      if: NOT type = cron AND NOT type = pull_request
      name: "on master"
      script:
        - echo "on master"
